spring.application.name=TechAlert

spring.datasource.url=jdbc:postgresql://localhost:2508/postgres
spring.datasource.username=postgres
spring.datasource.password=lucas12
spring.datasource.driver-class-name=org.postgresql.Driver
