spring.config.import=optional:classpath:application-local.properties

spring.datasource.url=jdbc:postgresql://localhost:2508/postgres
spring.datasource.username=${TECHALERT_DB_USERNAME}
spring.datasource.password=${TECHALERT_DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
server.address=0.0.0.0

